import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';import {spawnSync} from 'node:child_process';
const root=new URL('../',import.meta.url),read=async p=>readFile(new URL(p,root),'utf8');
const d=JSON.parse(await read('data/economic-dashboard.json'));
const near=(a,b,e=.02)=>assert.ok(Math.abs(a-b)<=e,`${a} != ${b}`);
test('dashboard generado es reproducible y tiene horizonte completo',()=>{const r=spawnSync(process.execPath,['scripts/build-economic-dashboard.js'],{cwd:new URL(root),encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.equal(d.months.length,24);assert.equal(d.years.length,5);assert.deepEqual(d.months.map(x=>x.id),Array.from({length:24},(_,i)=>`M${String(i+1).padStart(2,'0')}`));});
test('reconciliación mensual y anual',()=>{for(const x of d.months){near(x.revenuePhysical+x.revenueOnline+x.revenueRetreats,x.revenueTotal);near(x.variableCosts+x.contribution,x.revenueTotal);near(x.contribution-x.fixedOpex-x.somaOSCost,x.operatingFcf);near(x.operatingFcf-x.capex,x.netCashFlow);assert.ok(Object.values(x).every(v=>typeof v!=='number'||Number.isFinite(v)));}for(const y of d.years){const ms=d.months.slice((y.year-1)*12,y.year*12);if(ms.length===12){near(ms.reduce((a,x)=>a+x.revenueTotal,0),y.revenueTotal,.08);near(ms.reduce((a,x)=>a+x.operatingFcf,0),y.fcf,.08);}}near(d.months.at(-1).cashAccumulated,d.summary.capitalLeanRecommended+d.months.reduce((a,x)=>a+x.netCashFlow,0),.08);});
test('escenarios, evidencia y separación OS',()=>{assert.deepEqual(d.scenarios.map(x=>x.id),['lean','conservative','base','expansive','stress']);assert.equal(d.engines.somaOS.externalSaasRevenueBase24m,0);assert.equal(d.engines.onlineSchool.base24m.revenue,0);assert.equal(d.engines.retreats.base24m.revenue,0);assert.ok(d.assumptions.every(x=>['CONFIRMADO','DERIVADO','ESTIMADO','HIPÓTESIS','PENDIENTE'].includes(x.status)));});
test('HTML económico tiene secciones, render y IDs únicos',async()=>{const html=await read('modelo-economico.html');for(const id of ['resumen','arquitectura','inversion','capex','working-capital','opex','unit-economics','presencial','online','retreats','soma-os','year-one','months-24','cash-flow','break-even','payback','scenarios','sensitivity','years-five','hybrid','risks','assumptions','sources'])assert.match(html,new RegExp(`id="${id}"`));assert.match(html,/economic-dashboard\.js/);const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length);});
test('referencias locales del dashboard existen',async()=>{for(const p of d.sources)await assert.doesNotReject(()=>read(p));const files=await readdir(new URL('.',root));assert.ok(files.includes('modelo-economico.html'));});
